dist: xenial
language: python

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
env:
  - CC=gcc-7 CXX=g++-7

before_install:
  - ${CC} --version
  - ${CXX} --version
  - cmake --version
  - pip install -r test/python/requirements.txt

install:
   - mkdir build
   - cd build
   - cmake ../ -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=${CXX}
   - make install
   - cd ..

after_success:
   - codecov

jobs:
  include:
    - name: cpp
      script:
         - ./build/test/test_database
         - ./build/test/test_processes
      after_success: " "
    - name: cmake
      script:
      - mkdir test/cmake/build
      - cd test/cmake/build
      - CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:../../../build cmake ../ -DCMAKE_CXX_COMPILER=${CXX}
      - make
      - ./main
      after_success: " "
    - name: python 3.7
      python: 3.7
      install: pip install .
      script: pytest
    - name: python 3.8
      python: 3.8
      install: pip install .
      script: pytest
