dist: xenial
language: python

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" g++=g++-7 gcc=gcc-7

before_install:
  - eval "${MATRIX_EVAL}"
  - ${CC} --version
  - ${CXX} --version
  - cmake --version
  - pip install -r test/python/requirements.txt

install:
   - mkdir build
   - cd build
   - cmake ../ -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=${CXX}
   - make install
   - cd ..

jobs:
  include:
    - name: cpp
      script: for f in ./build/test/test_*; do ./$f; done
    - name: cmake
      script:
      - mkdir test/cmake/build
      - cd test/cmake/build
      - CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:../../../build cmake ../ -DCMAKE_CXX_COMPILER=${CXX}
      - make
      - ./main
    - name: python 3.7
      python: 3.7
      install: pip install .
      script: pytest
    - name: python 3.8
      python: 3.8
      install: pip install .
      script: pytest
