dist: xenial
language: python

os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake
env:
- CC=gcc-7 CXX=g++-7

before_install:
- ${CC} --version
- ${CXX} --version
- cmake --version
- pip install --force-reinstall -r test/python/requirements.txt

install:
- mkdir build
- cd build
- cmake ../ -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=${CXX}
- make install
- cd ..

jobs:
  include:
  - name: cpp
    script:
    - ./build/test/test_elements
    - ./build/test/test_database
    - ./build/test/test_processes
    after_success: " "
  - name: cmake
    python: 3.7
    script:
    - cd test/cmake
    - python build-and-run.py
    after_success: " "
  - name: format
    python: 3.7
    install: " "
    script:
    - python setup.py check_format --regex '(include|python|test|docs|scripts)'
    - python setup.py check_pyflakes --regex '(python|test|docs|scripts)'
  - name: module
    python: 3.7
    install: pip install .
    script:
    - python -m reactions print-table
    - python -m reactions check-syntax --decays 'A -> B C' --reactions 'A B -> C D' --kind string
  - name: python 3.7
    python: 3.7
    install: pip install .
    script: pytest
  - name: python 3.8
    python: 3.8
    install: pip install .
    script: pytest
    after_success: if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then codecov; fi
  - name: deploy
    if: branch = devel || branch = master
    python: 3.7
    before_deploy:
    # Define the Git configuration
    - git config --local user.name "Miguel Ramos Pernas"
    - git config --local user.email "miguel.ramos.pernas@gmail.com"
    # Export the path to the package
    - export PYTHONPATH=${PYTHONPATH}:python
    # Define the new and previous tags
    - export NEW_TAG=v$(python -c "import reactions; print(reactions.__version__)")
    - if [[ ! ${NEW_TAG} =~ "dev" ]]; then export EXCLUDE_PATTERN='*dev*'; fi
    - export LATEST_TAG=$(git describe --tags $(git rev-list --exclude=${EXCLUDE_PATTERN} --tags --max-count=1))
    - if [[ -z ${NEW_TAG} || -z ${LATEST_TAG} ]]; then exit 1; fi
    # Change the name of the tag if we are not in master
    - if [ ${TRAVIS_BRANCH} != master ]; then export TRAVIS_TAG=devel-${NEW_TAG}; else export TRAVIS_TAG=${NEW_TAG}; fi
    # Install Ruby and github_changelog_generator
    - sudo apt-get update
    - sudo apt-get install -y ruby
    - ruby --version
    - gem install github_changelog_generator
    # Generate the changelog file
    - ./repository changelog -o ${NEW_TAG}-changelog.md --since-tag ${LATEST_TAG} --future-release ${NEW_TAG} -t ${GITHUB_TOKEN}
    - ./repository changelog -o ${NEW_TAG}-full-changelog.md --since-tag v0.0.0 --future-release ${NEW_TAG} -t ${GITHUB_TOKEN}
    before_install: " "
    install: " "
    script: " "
    deploy:
        provider: releases
        token: ${GITHUB_TOKEN}
        tag_name: ${TRAVIS_TAG}
        name: ${TRAVIS_TAG}
        file:
        - ${NEW_TAG}-changelog.md
        - ${NEW_TAG}-full-changelog.md
        skip_cleanup: true
        draft: true
        on:
          branch:
          - devel
          - master
